package LEXICAL;

public enum TokenType
{
    // CLAUSE
    CREATE, DROP, SELECT, WHERE, INSERT,

    //DataType
    INT, STRING,

    //Keywords
    TABLE, FROM, INTO, PRIMARY, KEY, FOREIGN, REFERENCES, INDEX, JOIN, ON,
    AS, GROUP, BY, HAVING, ORDER, ASC, DESC, COUNT, SUM, AVG, MIN, MAX,

    // Symbols
    COMMA, STAR, LPAREN, RPAREN, EQUAL, NOT_EQUAL, LESS_THAN, LESS_THAN_EQUAL,
    GREATER_THAN, GREATER_THAN_EQUAL, DOT, SEMICOLON, AND,

    // Literals
    IDENTIFIER, STRING_LITERAL, NUMERIC_LITERAL,

    // Special
    EOF, // End of input
    INVALID // For malformed tokens
}
//ALSO UPDATE NEW TOKEN ADDITION IN LEXER - keywords MAP
